# Generated by Django 2.2 on 2021-11-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_value',
            field=models.CharField(default=None, max_length=10000000),
        ),
    ]
