# Generated by Django 2.2 on 2021-11-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_message_encrypted_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encrypted_value',
            field=models.CharField(default='null', max_length=10000000),
        ),
    ]
