# Generated by Django 2.2 on 2021-11-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_auto_20211128_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encrypted_value',
            field=models.CharField(max_length=10000000),
        ),
    ]
