# Generated by Django 2.2 on 2021-11-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_auto_20211128_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encrypted_value',
        ),
    ]
